"""
Streamlit Dashboard for Gold Price Forecasting
Real-time predictions, model comparison, and data visualization
"""

import os
import sys
import json
import time
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Dict, Any, List

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import yaml
import requests

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Page config
st.set_page_config(
    page_title="Gold Price Forecasting",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Configuration
CONFIG_PATH = Path(__file__).parent.parent / "config.yaml"


def load_config() -> Dict[str, Any]:
    """Load configuration with fallback to defaults"""
    default_config = {
        "server": {"host": "0.0.0.0", "port": 8000, "workers": 1},
        "dashboard": {"refresh_interval": 300, "port": 8501},
        "database": {
            "host": "localhost",
            "port": 5432,
            "name": "gold_forecast",
            "user": "postgres",
            "password": "postgres",
        },
        "api": {"metalpriceapi_key": ""},
        "models": {
            "lstm": {"sequence_length": 60, "layers": 2, "units": 50},
            "prophet": {},
            "arima": {},
        },
        "training": {"test_size": 0.2, "random_state": 42, "n_splits": 5},
        "forecast": {"horizon": 30, "confidence_level": 0.95},
        "monitoring": {"drift_threshold": 0.05, "retrain_frequency": "weekly"},
    }

    try:
        with open(CONFIG_PATH, "r") as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        return default_config


config = load_config()


class APIClient:
    """Client for interacting with the FastAPI backend"""

    def __init__(self, base_url: str = None):
        # Use environment variable or default to localhost
        self.base_url = base_url or os.environ.get("API_URL", "http://localhost:8000")

    def get_health(self) -> Dict[str, Any]:
        """Get API health status"""
        try:
            response = requests.get(f"{self.base_url}/health", timeout=5)
            return response.json()
        except:
            return {"status": "offline", "models_loaded": False}

    def get_predictions(self, model_type: str = "all", horizon: int = 7) -> List[Dict]:
        """Get predictions"""
        try:
            response = requests.post(
                f"{self.base_url}/predict",
                json={"model_type": model_type, "horizon": horizon},
                timeout=30,
            )
            return response.json()
        except:
            # Return demo predictions when API is unavailable
            return self._get_demo_predictions(horizon)

    def _get_demo_predictions(self, horizon: int) -> List[Dict]:
        """Generate demo predictions for standalone mode"""
        base_price = 1736.0
        predictions = [base_price + i * 0.3 for i in range(horizon)]
        return [
            {
                "model_type": "demo",
                "predictions": predictions,
                "lower_bound": [p - 20 for p in predictions],
                "upper_bound": [p + 20 for p in predictions],
                "horizon": horizon,
                "timestamp": datetime.now().isoformat(),
            }
        ]

    def get_metrics(self) -> List[Dict]:
        """Get model metrics"""
        try:
            response = requests.get(f"{self.base_url}/metrics", timeout=10)
            response.raise_for_status()
            return response.json()
        except:
            # Return demo metrics
            return [
                {"model_type": "demo_arima", "mae": 15.2, "rmse": 22.1, "mape": 0.87}
            ]

    def get_trained_forecasts(
        self, model_type: str = "all", horizon: Optional[int] = None
    ) -> List[Dict]:
        """Get persisted future forecasts generated by the training pipeline."""
        try:
            params: Dict[str, Any] = {"model_type": model_type}
            if horizon is not None:
                params["horizon"] = horizon

            response = requests.get(
                f"{self.base_url}/forecasts/trained", params=params, timeout=10
            )
            response.raise_for_status()
            return response.json()
        except Exception:
            return []

    def get_latest_data(self, days: int = 90) -> Dict:
        """Get latest price data"""
        try:
            response = requests.get(
                f"{self.base_url}/data/latest?days={days}", timeout=10
            )
            return response.json()
        except:
            # Return demo data
            dates = pd.date_range(end=datetime.now(), periods=days, freq="D")
            np.random.seed(42)
            prices = 1700 + np.cumsum(np.random.randn(days) * 5)
            return {
                "dates": [d.strftime("%Y-%m-%d") for d in dates],
                "prices": prices.tolist(),
                "volumes": [None] * days,
            }


def load_sample_data() -> pd.DataFrame:
    """Generate sample data for demo"""
    dates = pd.date_range(start="2023-01-01", end="2024-01-01", freq="D")
    np.random.seed(42)
    prices = 1800 + np.cumsum(np.random.randn(len(dates)) * 8)

    return pd.DataFrame({"gold_price": prices}, index=dates)


def normalize_metrics_payload(metrics: Any) -> List[Dict[str, Any]]:
    """Normalize API metrics payload into a list of records for plotting/table views."""
    if metrics is None:
        return []

    normalized: List[Dict[str, Any]] = []

    if isinstance(metrics, list):
        for item in metrics:
            if isinstance(item, dict):
                normalized.append(item)
    elif isinstance(metrics, dict):
        if {"model_type", "mae", "rmse", "mape"}.issubset(metrics.keys()):
            normalized.append(metrics)
        elif "metrics" in metrics and isinstance(metrics["metrics"], dict):
            for model_name, values in metrics["metrics"].items():
                if isinstance(values, dict):
                    normalized.append({"model_type": model_name, **values})
        else:
            for model_name, values in metrics.items():
                if isinstance(values, dict) and {"mae", "rmse", "mape"}.issubset(
                    values.keys()
                ):
                    normalized.append({"model_type": model_name, **values})

    sanitized: List[Dict[str, Any]] = []
    for row in normalized:
        model_name = row.get("model_type")
        mae = row.get("mae")
        rmse = row.get("rmse")
        mape = row.get("mape")
        if model_name is None:
            continue
        try:
            sanitized.append(
                {
                    "model_type": str(model_name),
                    "mae": float(mae),
                    "rmse": float(rmse),
                    "mape": float(mape),
                }
            )
        except (TypeError, ValueError):
            continue

    return sanitized


def normalize_trained_forecasts_payload(payload: Any) -> List[Dict[str, Any]]:
    """Normalize trained forecasts payload into a consistent list shape."""
    records: List[Dict[str, Any]] = []

    if isinstance(payload, list):
        for item in payload:
            if isinstance(item, dict):
                records.append(item)
    elif isinstance(payload, dict):
        for name, values in payload.items():
            if not isinstance(values, dict):
                continue
            records.append({"model_type": name, **values})

    normalized: List[Dict[str, Any]] = []
    for row in records:
        model_type = row.get("model_type")
        dates = row.get("dates") or []
        predictions = row.get("predictions") or []
        if not model_type or not isinstance(dates, list) or not isinstance(predictions, list):
            continue

        usable_horizon = min(len(dates), len(predictions))
        if usable_horizon == 0:
            continue

        try:
            normalized.append(
                {
                    "model_type": str(model_type),
                    "horizon": int(row.get("horizon", usable_horizon)),
                    "dates": [str(item) for item in dates[:usable_horizon]],
                    "predictions": [float(item) for item in predictions[:usable_horizon]],
                    "source": str(row.get("source", "trained_results")),
                }
            )
        except (TypeError, ValueError):
            continue

    return normalized


def get_plotly_template() -> str:
    """Resolve plotly template based on selected UI theme."""
    return "plotly" if st.session_state.get("theme_mode", "Dark") == "Light" else "plotly_dark"


def inject_custom_styles(
    theme_mode: str = "Dark", compact_mode: bool = False, reduce_motion: bool = False
) -> None:
    """Inject custom CSS for modern, consistent UI with theme, density, and motion controls."""
    is_light = theme_mode == "Light"
    panel_bg = "#FFFFFF" if is_light else "rgba(255,255,255,0.02)"
    metric_border = "rgba(15, 23, 42, 0.12)" if is_light else "rgba(255,255,255,0.10)"
    section_color = "#111827" if is_light else "#F8FAFC"
    caption_color = "#374151" if is_light else "rgba(248,250,252,0.80)"
    empty_border = "rgba(15, 23, 42, 0.28)" if is_light else "rgba(255,255,255,0.25)"
    status_border = "rgba(15, 23, 42, 0.2)" if is_light else "rgba(255,255,255,0.25)"
    hero_gradient = (
        "linear-gradient(135deg, rgba(255,215,0,0.24), rgba(255,255,255,0.92))"
        if is_light
        else "linear-gradient(135deg, rgba(255,215,0,0.20), rgba(46,52,64,0.65))"
    )
    container_top = "0.85rem" if compact_mode else "1.3rem"
    container_bottom = "0.6rem" if compact_mode else "1rem"
    metric_padding = "0.42rem" if compact_mode else "0.7rem"
    tab_padding = "0.3rem 0.65rem" if compact_mode else "0.4rem 0.9rem"
    section_margin_top = "0.55rem" if compact_mode else "1rem"
    section_margin_bottom = "0.1rem" if compact_mode else "0.2rem"
    section_caption_bottom = "0.45rem" if compact_mode else "0.7rem"
    hero_padding = "0.9rem 1rem" if compact_mode else "1.2rem 1.25rem"
    animate_duration = "0.42s" if compact_mode else "0.55s"

    css_template = """
        <style>
            .main .block-container {
                padding-top: __CONTAINER_TOP__;
                padding-bottom: __CONTAINER_BOTTOM__;
                max-width: 1180px;
            }
            .app-hero {
                padding: __HERO_PADDING__;
                border-radius: 14px;
                background: __HERO_GRADIENT__;
                border: 1px solid rgba(255, 215, 0, 0.30);
                margin-bottom: 1rem;
            }
            .app-hero h1 {
                margin: 0;
                font-size: 1.8rem;
                color: __SECTION_COLOR__;
            }
            .app-hero p {
                margin-top: 0.25rem;
                margin-bottom: 0;
                opacity: 0.9;
                color: __CAPTION_COLOR__;
            }
            .section-title {
                font-size: 1.15rem;
                font-weight: 650;
                margin-top: __SECTION_MARGIN_TOP__;
                margin-bottom: __SECTION_MARGIN_BOTTOM__;
                color: __SECTION_COLOR__;
            }
            .section-caption {
                color: __CAPTION_COLOR__;
                margin-bottom: __SECTION_CAPTION_BOTTOM__;
            }
            .status-pill {
                display: inline-block;
                padding: 0.25rem 0.55rem;
                border-radius: 999px;
                font-size: 0.78rem;
                font-weight: 600;
                margin-right: 0.4rem;
                border: 1px solid __STATUS_BORDER__;
            }
            .status-ok {
                background: rgba(25, 195, 125, 0.18);
                color: #9af0c9;
            }
            .status-warn {
                background: rgba(255, 177, 66, 0.16);
                color: #ffd58f;
            }
            .status-bad {
                background: rgba(255, 99, 132, 0.16);
                color: #ffb3c4;
            }
            .empty-state {
                padding: 1rem;
                border-radius: 12px;
                border: 1px dashed __EMPTY_BORDER__;
                opacity: 0.9;
                margin-top: 0.4rem;
            }
            .stMetric {
                border: 1px solid __METRIC_BORDER__;
                border-radius: 12px;
                padding: __METRIC_PADDING__;
                background: __PANEL_BG__;
            }
            [data-testid="stDataFrame"] {
                border-radius: 10px;
                overflow: hidden;
            }
            .stTabs [data-baseweb="tab-list"] {
                gap: 0.5rem;
            }
            .stTabs [data-baseweb="tab"] {
                border-radius: 8px;
                padding: __TAB_PADDING__;
            }
            .animate-in {
                animation: fadeUp __ANIMATE_DURATION__ ease-out both;
            }
            .animate-delay-1 {
                animation-delay: 0.05s;
            }
            .animate-delay-2 {
                animation-delay: 0.10s;
            }
            @keyframes fadeUp {
                0% {
                    opacity: 0;
                    transform: translateY(8px);
                }
                100% {
                    opacity: 1;
                    transform: translateY(0);
                }
            }
            __MOTION_OVERRIDE__
            @media (max-width: 900px) {
                .main .block-container {
                    padding-top: 0.8rem;
                    padding-left: 0.8rem;
                    padding-right: 0.8rem;
                }
                .app-hero {
                    padding: 0.9rem;
                }
                .app-hero h1 {
                    font-size: 1.35rem;
                }
                .app-hero p {
                    font-size: 0.92rem;
                }
                .section-title {
                    font-size: 1.02rem;
                }
                .status-pill {
                    margin-bottom: 0.35rem;
                }
            }
        </style>
    """

    css = (
        css_template.replace("__HERO_GRADIENT__", hero_gradient)
        .replace("__SECTION_COLOR__", section_color)
        .replace("__CAPTION_COLOR__", caption_color)
        .replace("__STATUS_BORDER__", status_border)
        .replace("__EMPTY_BORDER__", empty_border)
        .replace("__METRIC_BORDER__", metric_border)
        .replace("__PANEL_BG__", panel_bg)
        .replace("__CONTAINER_TOP__", container_top)
        .replace("__CONTAINER_BOTTOM__", container_bottom)
        .replace("__METRIC_PADDING__", metric_padding)
        .replace("__TAB_PADDING__", tab_padding)
        .replace("__SECTION_MARGIN_TOP__", section_margin_top)
        .replace("__SECTION_MARGIN_BOTTOM__", section_margin_bottom)
        .replace("__SECTION_CAPTION_BOTTOM__", section_caption_bottom)
        .replace("__HERO_PADDING__", hero_padding)
        .replace("__ANIMATE_DURATION__", animate_duration)
        .replace(
            "__MOTION_OVERRIDE__",
            "@media (prefers-reduced-motion: reduce){.animate-in{animation:none!important;}}"
            if not reduce_motion
            else ".animate-in{animation:none !important;} .animate-delay-1{animation-delay:0s;} .animate-delay-2{animation-delay:0s;}",
        )
    )

    st.markdown(css, unsafe_allow_html=True)


def render_hero(health: Dict[str, Any]) -> None:
    """Render top hero section with compact status pills."""
    api_status = str(health.get("status", "unknown")).lower()
    api_class = "status-ok" if api_status == "healthy" else "status-bad"

    db_connected = bool(health.get("database_connected"))
    db_class = "status-ok" if db_connected else "status-warn"

    model_count = len(health.get("available_models", []))
    model_class = "status-ok" if model_count > 0 else "status-warn"

    st.markdown(
        f"""
        <div class="app-hero animate-in">
            <h1>📈 Gold Price Forecasting</h1>
            <p>Production dashboard for XAU/USD forecasting with Prophet, ARIMA, and LSTM.</p>
            <div style="margin-top: 0.65rem;">
                <span class="status-pill {api_class}">API: {api_status.title()}</span>
                <span class="status-pill {db_class}">Database: {'Connected' if db_connected else 'Unavailable'}</span>
                <span class="status-pill {model_class}">Models: {model_count}</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_section_header(title: str, caption: str) -> None:
    """Render section heading and caption."""
    st.markdown(
        f'<div class="section-title animate-in animate-delay-1">{title}</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        f'<div class="section-caption animate-in animate-delay-2">{caption}</div>',
        unsafe_allow_html=True,
    )


def render_empty_state(message: str) -> None:
    """Render consistent empty-state message."""
    st.markdown(
        f'<div class="empty-state animate-in">ℹ️ {message}</div>',
        unsafe_allow_html=True,
    )


def plot_price_chart(
    df: pd.DataFrame, title: str = "Gold Price (XAU/USD)"
) -> go.Figure:
    """Create interactive price chart"""
    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=df.index,
            y=df["gold_price"],
            mode="lines",
            name="Price",
            line=dict(color="#FFD700", width=2),
        )
    )

    fig.update_layout(
        title=title,
        xaxis_title="Date",
        yaxis_title="Price (USD)",
        template=get_plotly_template(),
        height=400,
        hovermode="x unified",
    )

    return fig


def plot_predictions(
    actual: list, predictions: Dict[str, list], dates: list
) -> go.Figure:
    """Plot actual vs predicted prices"""
    fig = go.Figure()

    # Actual prices
    fig.add_trace(
        go.Scatter(
            x=dates[: len(actual)],
            y=actual,
            mode="lines",
            name="Actual",
            line=dict(color="#00FF00", width=2),
        )
    )

    colors = ["#FF6B6B", "#4ECDC4", "#45B7D1"]

    for i, (model_name, preds) in enumerate(predictions.items()):
        fig.add_trace(
            go.Scatter(
                x=dates[: len(preds)],
                y=preds,
                mode="lines",
                name=f"{model_name} Prediction",
                line=dict(color=colors[i % len(colors)], width=2, dash="dash"),
            )
        )

    fig.update_layout(
        title="Actual vs Predicted Prices",
        xaxis_title="Date",
        yaxis_title="Price (USD)",
        template=get_plotly_template(),
        height=400,
        hovermode="x unified",
    )

    return fig


def plot_metrics_comparison(metrics: List[Dict]) -> go.Figure:
    """Create metrics comparison chart"""
    normalized_metrics = normalize_metrics_payload(metrics)
    if not normalized_metrics:
        return go.Figure()

    df = pd.DataFrame(normalized_metrics)

    fig = make_subplots(
        rows=1,
        cols=3,
        subplot_titles=("MAE", "RMSE", "MAPE (%)"),
        horizontal_spacing=0.1,
    )

    models = df["model_type"].tolist()
    colors = ["#FF6B6B", "#4ECDC4", "#45B7D1"][: len(models)]

    # MAE
    fig.add_trace(
        go.Bar(x=models, y=df["mae"], name="MAE", marker_color=colors), row=1, col=1
    )

    # RMSE
    fig.add_trace(
        go.Bar(x=models, y=df["rmse"], name="RMSE", marker_color=colors), row=1, col=2
    )

    # MAPE
    fig.add_trace(
        go.Bar(x=models, y=df["mape"], name="MAPE", marker_color=colors), row=1, col=3
    )

    fig.update_layout(
        title="Model Performance Comparison",
        template=get_plotly_template(),
        showlegend=False,
        height=350,
    )

    return fig


def plot_forecast_with_confidence(
    dates: list, predictions: list, lower: list, upper: list
) -> go.Figure:
    """Plot forecast with confidence intervals"""
    fig = go.Figure()

    # Confidence interval
    fig.add_trace(
        go.Scatter(
            x=dates + dates[::-1],
            y=upper + lower[::-1],
            fill="toself",
            fillcolor="rgba(255, 215, 0, 0.2)",
            line=dict(color="rgba(255,255,255,0)"),
            name="Confidence Interval",
        )
    )

    # Predictions
    fig.add_trace(
        go.Scatter(
            x=dates,
            y=predictions,
            mode="lines",
            name="Prediction",
            line=dict(color="#FFD700", width=2),
        )
    )

    fig.update_layout(
        title="Price Forecast with Confidence Interval",
        xaxis_title="Date",
        yaxis_title="Price (USD)",
        template=get_plotly_template(),
        height=400,
    )

    return fig


def plot_volatility(df: pd.DataFrame) -> go.Figure:
    """Plot price volatility"""
    returns = df["gold_price"].pct_change() * 100

    fig = go.Figure()

    fig.add_trace(
        go.Bar(
            x=df.index[1:],
            y=returns[1:],
            name="Daily Returns %",
            marker_color=np.where(returns[1:] > 0, "#00FF00", "#FF0000"),
        )
    )

    fig.update_layout(
        title="Daily Returns Volatility",
        xaxis_title="Date",
        yaxis_title="Return (%)",
        template=get_plotly_template(),
        height=300,
    )

    return fig


def plot_correlation_matrix(df: pd.DataFrame) -> go.Figure:
    """Plot correlation matrix"""
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    corr = df[numeric_cols].corr()

    fig = px.imshow(
        corr,
        text_auto=True,
        color_continuous_scale="RdYlGn",
        title="Feature Correlation Matrix",
    )

    fig.update_layout(template=get_plotly_template(), height=400)

    return fig


def main():
    """Main Streamlit app"""
    if "theme_mode" not in st.session_state:
        st.session_state["theme_mode"] = "Dark"
    if "compact_mode" not in st.session_state:
        st.session_state["compact_mode"] = False
    if "enable_animations" not in st.session_state:
        st.session_state["enable_animations"] = True

    st.sidebar.markdown("## ⚙️ Control Center")
    theme_mode = st.sidebar.selectbox(
        "Theme",
        ["Dark", "Light"],
        index=0 if st.session_state.get("theme_mode", "Dark") == "Dark" else 1,
        help="Switch between visual themes for better readability.",
    )
    st.session_state["theme_mode"] = theme_mode

    compact_mode = st.sidebar.toggle(
        "Compact Mode",
        value=st.session_state.get("compact_mode", False),
        help="Use a denser layout for tables and cards.",
    )
    st.session_state["compact_mode"] = compact_mode

    enable_animations = st.sidebar.toggle(
        "Section Animations",
        value=st.session_state.get("enable_animations", True),
        help="Enable subtle transitions for section elements.",
    )
    st.session_state["enable_animations"] = enable_animations

    inject_custom_styles(
        theme_mode=theme_mode,
        compact_mode=compact_mode,
        reduce_motion=not enable_animations,
    )

    api_url = st.sidebar.text_input("Backend URL", "http://localhost:8000")

    refresh_enabled = st.sidebar.toggle("Auto Refresh", value=False)
    refresh_interval = st.sidebar.selectbox("Refresh every", [30, 60, 120, 300], 1)
    st.sidebar.caption("Use auto-refresh for live tracking when the API is running.")

    st.sidebar.markdown("---")
    page = st.sidebar.radio(
        "Navigate",
        ["Dashboard", "Predictions", "Model Comparison", "Data Analysis"],
        captions=[
            "Live market overview",
            "Generate multi-model forecasts",
            "Compare model quality",
            "Explore distributions and trends",
        ],
    )

    st.sidebar.markdown("---")
    st.sidebar.caption(f"Session time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    st.sidebar.caption("Tip: Use Light theme in bright environments.")
    st.sidebar.caption("Tip: Enable compact mode for smaller screens.")

    api = APIClient(api_url)

    if refresh_enabled:
        time.sleep(refresh_interval)
        st.rerun()

    health = api.get_health()
    render_hero(health)

    status_col_1, status_col_2, status_col_3, status_col_4 = st.columns(4)
    with status_col_1:
        st.metric("API Status", str(health.get("status", "unknown")).title())
    with status_col_2:
        st.metric("Models Loaded", len(health.get("available_models", [])))
    with status_col_3:
        st.metric("Database", "Connected" if health.get("database_connected") else "Unavailable")
    with status_col_4:
        latest_price = health.get("latest_price")
        st.metric("Latest Price", f"${latest_price:,.2f}" if latest_price else "N/A")

    if page == "Dashboard":
        render_section_header(
            "Dashboard", "Track the latest price action and forecast signals at a glance."
        )

        data = api.get_latest_data(90)

        if data.get("prices"):
            df = pd.DataFrame(
                {"gold_price": data["prices"]}, index=pd.to_datetime(data["dates"])
            )
        else:
            df = load_sample_data()
            st.info("Live data unavailable, showing sample data.")

        overview_tab, forecast_tab = st.tabs(["📈 Market Overview", "🔮 Forecast Snapshot"])

        with overview_tab:
            st.plotly_chart(plot_price_chart(df), use_container_width=True)

            kpi_col_1, kpi_col_2, kpi_col_3, kpi_col_4 = st.columns(4)
            latest = float(df["gold_price"].iloc[-1])
            previous = float(df["gold_price"].iloc[-2]) if len(df) > 1 else latest
            daily_delta = latest - previous
            daily_delta_pct = (daily_delta / previous * 100) if previous else 0

            with kpi_col_1:
                st.metric("Current Price", f"${latest:,.2f}")
            with kpi_col_2:
                st.metric("Daily Change", f"${daily_delta:,.2f}", f"{daily_delta_pct:.2f}%")
            with kpi_col_3:
                st.metric("90-day High", f"${df['gold_price'].max():,.2f}")
            with kpi_col_4:
                st.metric("90-day Low", f"${df['gold_price'].min():,.2f}")

            st.plotly_chart(plot_volatility(df), use_container_width=True)

        with forecast_tab:
            horizon = st.slider("Forecast Horizon (days)", 1, 30, 7, key="dashboard_horizon")
            forecast_source = st.radio(
                "Forecast Source",
                ["Live Model Inference", "Latest Trained Forecast"],
                horizontal=True,
                key="dashboard_forecast_source",
            )

            if forecast_source == "Latest Trained Forecast":
                predictions = normalize_trained_forecasts_payload(
                    api.get_trained_forecasts("all", horizon)
                )
            else:
                predictions = api.get_predictions("all", horizon)

            if predictions:
                for pred in predictions[:3]:
                    model_name = str(pred.get("model_type", "model")).upper()
                    model_preds = pred.get("predictions", [])
                    if not model_preds:
                        continue

                    with st.expander(f"{model_name} • next {horizon} days", expanded=model_name == "ARIMA"):
                        days_to_show = min(7, len(model_preds))
                        preview_df = pd.DataFrame(
                            {
                                "Day": [f"Day {i+1}" for i in range(days_to_show)],
                                "Forecast": [float(x) for x in model_preds[:days_to_show]],
                            }
                        )
                        st.dataframe(
                            preview_df.style.format({"Forecast": "${:,.2f}"}),
                            use_container_width=True,
                        )
            else:
                render_empty_state("No predictions available yet. Train models or verify API connectivity.")

    elif page == "Predictions":
        render_section_header(
            "Predictions",
            "Generate forward-looking forecasts and confidence intervals for any model.",
        )

        mode = st.radio(
            "Prediction Mode",
            ["Live Inference", "Latest Trained Forecast"],
            horizontal=True,
            key="prediction_mode",
        )

        input_col_1, input_col_2, input_col_3 = st.columns([1.2, 1.2, 0.9])
        with input_col_1:
            model_choice = st.selectbox(
                "Model", ["all", "prophet", "arima", "lstm"], key="predictions_model"
            )
        with input_col_2:
            horizon = st.slider("Horizon (days)", 1, 30, 7, key="predictions_horizon")
        with input_col_3:
            st.markdown("<div style='height: 1.7rem;'></div>", unsafe_allow_html=True)
            run_prediction = st.button("Generate Forecast", type="primary", use_container_width=True)

        if run_prediction:
            with st.spinner("Fetching predictions..."):
                if mode == "Latest Trained Forecast":
                    predictions = normalize_trained_forecasts_payload(
                        api.get_trained_forecasts(model_choice, horizon)
                    )
                else:
                    predictions = api.get_predictions(model_choice, horizon)

                if predictions:
                    for pred in predictions:
                        if not pred.get("predictions"):
                            continue

                        model_name = str(pred.get("model_type", "model")).upper()
                        dates = (
                            pd.date_range(
                                start=datetime.now(), periods=pred["horizon"], freq="D"
                            )
                            .strftime("%Y-%m-%d")
                            .tolist()
                        )

                        fig = plot_forecast_with_confidence(
                            dates,
                            pred["predictions"],
                            pred.get("lower_bound", []),
                            pred.get("upper_bound", []),
                        )

                        fig.update_layout(title=f"{model_name} Forecast", height=420)
                        st.plotly_chart(fig, use_container_width=True)

                        st.success(
                            f"Generated {pred['horizon']}-day forecast using {pred['model_type']}"
                        )
                else:
                    render_empty_state("No predictions available. Train models first.")

    elif page == "Model Comparison":
        render_section_header(
            "Model Comparison",
            "Compare error metrics and identify the most reliable model quickly.",
        )

        with st.spinner("Loading metrics..."):
            metrics = normalize_metrics_payload(api.get_metrics())

            if metrics:
                df_metrics = pd.DataFrame(metrics).sort_values("mape").reset_index(drop=True)

                summary_col_1, summary_col_2, summary_col_3 = st.columns(3)
                with summary_col_1:
                    st.metric("Best Model", df_metrics.iloc[0]["model_type"].upper())
                with summary_col_2:
                    st.metric("Best MAPE", f"{df_metrics.iloc[0]['mape']:.2f}%")
                with summary_col_3:
                    st.metric("Avg RMSE", f"{df_metrics['rmse'].mean():.2f}")

                # Metrics comparison
                st.plotly_chart(
                    plot_metrics_comparison(metrics), use_container_width=True
                )

                # Detailed metrics table
                render_section_header("Detailed Metrics", "Lower values indicate better model accuracy.")

                st.dataframe(
                    df_metrics.style.format(
                        {"mae": "{:.2f}", "rmse": "{:.2f}", "mape": "{:.2f}%"}
                    ),
                    use_container_width=True,
                )

                # Best model highlight
                best_model = df_metrics.iloc[0]["model_type"]
                best_mape = df_metrics.iloc[0]["mape"]

                st.success(
                    f"🏆 Best Model: {best_model.upper()} (MAPE: {best_mape:.2f}%)"
                )
            else:
                render_empty_state("No metrics available yet. Train models to populate this view.")

    elif page == "Data Analysis":
        render_section_header(
            "Data Analysis",
            "Explore trends, dispersion, and core descriptive statistics from historical prices.",
        )

        data = api.get_latest_data(365)

        if data.get("prices"):
            df = pd.DataFrame(
                {"gold_price": data["prices"]}, index=pd.to_datetime(data["dates"])
            )

            analysis_days = st.select_slider(
                "Analysis Window",
                options=[30, 60, 90, 180, 365],
                value=180,
            )
            df = df.tail(analysis_days)

            # Correlation matrix
            st.plotly_chart(plot_correlation_matrix(df), use_container_width=True)

            # Price distribution
            fig = px.histogram(
                df,
                x="gold_price",
                nbins=50,
                title="Price Distribution",
                color_discrete_sequence=["#FFD700"],
            )
            fig.update_layout(template=get_plotly_template())
            st.plotly_chart(fig, use_container_width=True)

            # Statistics
            st.subheader("📊 Statistics")

            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.metric("Mean", f"${df['gold_price'].mean():,.2f}")

            with col2:
                st.metric("Median", f"${df['gold_price'].median():,.2f}")

            with col3:
                st.metric("Std Dev", f"${df['gold_price'].std():,.2f}")

            with col4:
                st.metric(
                    "Coef of Var",
                    f"{(df['gold_price'].std() / df['gold_price'].mean() * 100):.2f}%",
                )
        else:
            render_empty_state("No data available for analysis.")


if __name__ == "__main__":
    main()
